version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: apexpacks
    main: ./cmd/apexpacks
    binary: apexpacks
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: apexpacks
    name_template: "apexpacks_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
