apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: apexpack-node-
spec:
  pipelineRef:
    name: apexpack-build-and-push
  params:
    - name: GIT_URL
      value: https://github.com/heroku/node-js-sample
    - name: GIT_REVISION
      value: main
    - name: IMAGE
      value: ttl.sh/node-sample:1h
    - name: RUNTIME
      value: node
    - name: FAIL_ON
      value: high
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: apexpack-source
    - name: profiles
      persistentVolumeClaim:
        claimName: apexpack-profiles
    - name: output
      persistentVolumeClaim:
        claimName: apexpack-output
